### ISSUE TITLE
The iOS template script is removing the download link for iPad Air 2 iOS 13.

### ISSUE THREAD

**Issue by d3signerd** [fastlane-community/fastlane-plugin-s3#79]
` <script type='text/javascript'>
    // if (/Android/i.test(navigator.userAgent))
    // {
    //   document.getElementById("ios").remove()
    //   document.getElementById("desktop").remove()
    // }
    if (/iPhone|iPad|iPod/i.test(navigator.userAgent))
    {
      // document.getElementById("android").remove()
      document.getElementById("desktop").remove()
    }
    else
    {
      document.getElementById("ios").remove()
      // document.getElementById("android").remove()
    }`

^^ This works fine on iPhone 7 running iOS 13.0 and iPads running iOS < 13.0.  But, for iPad devices running iOS 13 the `/iPhone|iPad|iPod/i.test(navigator.userAgent)` check removes the "iOS" span rather than the "desktop" one.  

This happens when trying to download in Safari.   

A work around, for now, is to open the links up in Chrome.

**Comment by troy-lamerton** [comment]
This seems to affect all devices running iPadOS 13.0.

Worth clarifying that there is no issue with running the app once it is installed. iPadOS runs the app just fine.

The issue is that the `index.html` page is not showing the download link on iPad's running iPadOS.

Though it is a hassle to copy the link and past into Chrome, that does work for now. I'm not using latest chrome.

**Comment by joshdholtz** [comment]
Released `1.6.1` with fixes for this!
